# Generated by Django 4.2.23 on 2025-07-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_unlockedlesson_delete_savedlesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='left_handed',
            field=models.BooleanField(default=False),
        ),
    ]
